### ISSUE TITLE
New Auto: Basic move forward auto

### ISSUE THREAD

**Issue by bbontrager89** [Auth-Xero/9430-offseasonSwerve#1]
**Auto Details**
Create a new auto that drives the robot forward and stops. 

**Affected Subsystems**
DriveSubsystem, Auto

**Commands Used**
None

**Additional Notes**
Issue #2  requires paths be auto-correcting and resilient to errors.

**Comment by salut-hi** [comment]
Test 12/5/24 -- 4:47pm
** Testing expectations
a. Robot moves forward relative to it's front autonomously 

**Test results
a. Robot won't make any sort of movement either in zeroing or direction

-- 5:00
a. Robot motors moved but not in the right direction. Also found an issue with one of the can ID's.

-- 5:09
a. Spark Max was unplugged (fixed). Motors moved but diagonal

-- 5:11
a. Direction is better but still not going straight. Unhappy encoder?

-- 5:12
a. Turned robot. Found a problem concerning the start point and end point. Commented out zeroHeading

-- 5:17
a. Staying in same starting position but the starting position is wrong. 

-- 5:39
a. Moved forward and slowed down *Passed Test*
