### ISSUE TITLE
Start working photonvision server on Pi

### ISSUE THREAD

**Issue by bbontrager89** [Auth-Xero/9430-offseasonSwerve#19]
## Problem Summary
There is no Photonvision on OrangePi. 

## Feature Summary
When Photonvision is installed on OrangePi, we will be able to see output from cameras and process Photonvision through the ArduCams. 

## Additional context
N/A

## Resources
[Another team on CD](https://www.chiefdelphi.com/t/issues-getting-photonvision-installed-on-an-orange-pi-5/473643) has had issues installing Photonvision on OrangePi 5. Here might be a good place to start looking into a tutorial on how to get Photonvision installed properly on the pi. 

Hint -- Much like installing it on a PC, you will likely need to figure out how to use an application repository manager to install photonvision onto Orange Pi. You can connect to the Pi using SSH or using an HDMI display.

**Comment by bbontrager89** [comment]
Blocks #3

**Comment by bbontrager89** [comment]
Here is a good place to get started. First, [set up our OrangePi](https://docs.photonvision.org/en/v2025.0.0-beta-1/docs/installation/sw_install/orange-pi.html) (updated)

Then, [install photon vision]. Looks like there's an [install script](https://raw.githubusercontent.com/PhotonVision/photonvision/master/scripts/install.sh) we can download and run via SSH for headless setup, but this issue may require us to set up a display. We might be able to borrow a monitor from the lab?

**Comment by IamIisI** [comment]
Step 1: Download [photonvision-v2025.0.0-beta-6-linuxarm64_orangepi5.img.xz](https://github.com/PhotonVision/photonvision/releases/download/v2025.0.0-beta-6/photonvision-v2025.0.0-beta-6-linuxarm64_orangepi5.img.xz)
Step 2: Use [Balena Etcher](https://github.com/balena-io/etcher/releases/tag/v1.18.11) to flash an SD card with the image
Step 3: Boot and install on the robot

**Comment by bbontrager89** [comment]
*Note: Existing MicroSD card found in the OrangePi, unknown state. Formatted w/ FAT32 and stored with SD Card reader on programming table in closet.*

**Comment by bbontrager89** [comment]
See [Networking Guide](https://docs.photonvision.org/en/latest/docs/quick-start/networking.html)

**Comment by IamIisI** [comment]
# Resolution Notes:
- After waiting around 10 minutes it was fully initialized
- Under ipconfig there was a wifi interface that listed the IPv4 under the address 10.94.30.24
- Connected to the photon vision server by using the port :5800
- According to the networking guide, we needed to access photonvision.local:5800 in a web browser
- Set the IP assignment mode to static
- Change team number from 0 to 9430
- Made static IP: 10.94.30.11
- Downloaded logs and Saved


[photonvision-logs.zip](https://github.com/user-attachments/files/18174517/photonvision-logs.zip)

This server is now fully accessible
